version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tmbDB;Username=postgres;Password=1234;SearchPath=public
      - ServiceBus__ConnectionString=SUA_CONNECTION_STRING
      - ServiceBus__QueueName=pedidos
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tmbDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: